### PR TITLE
Add readme for helpers functions / fix (?) regex

### PR DESCRIPTION
**Pull request by Jones-S**
Includes bit of documentation and maybe a regex fix:
See:
https://regex101.com/r/uMOB5V/2/
vs.
https://regex101.com/r/uMOB5V/3/

Used in 
https://github.com/wearelucid/vuecid-helpers/blob/master/src/url/getPathFromUrl.js

### CODE REVIEW

**Comment by Jones-S** [comment]
I removed the comment in `removeLeadingLang` because pages with a two-character slug will lose their slug... 
`https://meineseite.ch/ja/unterseite`.
We are probably good to go with it/fr/en/de

**Comment by marcoeh** [comment]
I like it. We could also keep the documentation right in our source code in [JSDoc](http://usejsdoc.org/) style and generate the docs with [documentation.js](https://github.com/documentationjs/documentation) ([HTML w/ GitHub Pages](http://documentation.js.org/html-example/) or [Markdown](https://github.com/documentationjs/documentation/blob/master/docs/NODE_API.md)) without the need of manually editing readme/doc files 🤖🚀.

**Comment by marcoeh** [comment]
Like [this](https://github.com/wearelucid/vuecid-helpers/blob/master/src/url/removeLeadingSlash.js#L4), but better and for real ;)

**Comment by marcoeh** [comment]
Maybe [VuePress](https://vuepress.vuejs.org/) with [this](https://github.com/ph1p/vuepress-jsdoc) would do the job pretty well.

**Comment by Jones-S** [comment]
Can we still merge this until somebody does the automatic doc generation?
I find myself navigating to the readme being disappointed by an empty readme.

**Comment by marcoeh** [comment]
Not-empty readme: https://github.com/wearelucid/vuecid-helpers/blob/b9072ea6c5ed92e2bacbd304025b78d66a09feab/README.md

**Pull request merged**
